# Generated by Django 5.2.7 on 2025-10-12 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c4c07649-7110-466d-8c13-c1ad5430fd53'), editable=False, help_text='ID for Categories', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Product.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2be5ac3c-88e1-403d-a539-d91514e7c644'), editable=False, help_text='ID for products', primary_key=True, serialize=False, verbose_name='product_id')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price of a Product')),
                ('currency', models.CharField(default='USD', max_length=20)),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='categories', to='Product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6dc40526-a073-4c82-aa35-a67be0e09f9f'), editable=False, primary_key=True, serialize=False, verbose_name='variant_id')),
                ('name', models.CharField(help_text="eg. 'size L / Red' ", max_length=100)),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price override; if blank, product.price is used', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Product.product')),
            ],
        ),
    ]
