# Generated by Django 5.2.7 on 2025-10-14 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64f0cce3-7bda-4a14-99a6-4ce7263738fc'), editable=False, help_text='ID for Categories', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43acfa75-5531-43ca-b858-367ac47ec9a8'), editable=False, help_text='ID for products', primary_key=True, serialize=False, verbose_name='product_id'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba1e0af1-48d9-460e-810b-efb424887636'), editable=False, primary_key=True, serialize=False, verbose_name='variant_id'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('78670bf1-1c31-4179-8359-8f6b78574693'), editable=False, primary_key=True, serialize=False, verbose_name='variant_id')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
