# Generated by Django 5.2.7 on 2025-10-19 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db602963-6109-486e-b6ea-3729e19dd18d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
