# Generated by Django 5.2.7 on 2025-10-12 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5287ab53-2087-460c-8182-336df6fe35e0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
