# Generated by Django 5.2.7 on 2025-10-14 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a42c49e-901b-4a3a-931d-5d4e086ac1cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
