# Generated by Django 5.2.7 on 2025-10-19 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e406bee-9a0b-478f-bb17-36a1f52008e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
