# Generated by Django 5.2.7 on 2025-10-19 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08a45b96-4f3e-48b5-8cf9-23ff597bb6a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
